server:
  port: 8080

spring:
  datasource:
    username: root
    password: sql_890my
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


# example values

indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru


# Настройки приложения
search-bot-settings:
  user-agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referer: http://www.google.com
  requests-interval:
    min: 500
    max: 1000